[window]
decorations = "None"
dynamic_padding = true

[mouse]
hide_when_typing = true

[scrolling]
history = 1000
multiplier = 10

[font]
normal = { family = "NotoSansMono", style = "SemiBold" }
size = 8.25

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[colors.normal]
white = "#ffffff"
black = "#000000"

[debug]
render_timer = false
