[window]
decorations = "None"
dynamic_padding = true

[mouse]
hide_when_typing = true

[scrolling]
history = 1000
multiplier = 10

[font]
normal = { family = "NotoSansMono", style = "SemiBold" }
size = 8.25

[colors.primary]
foreground = "#e5e5e0"
background = "#1a1a1f"

[debug]
render_timer = false
