[options]
SigLevel = Required DatabaseOptional TrustedOnly
DisableDownloadTimeout
HoldPkg = pacman glibc
ParallelDownloads = 8
Architecture = auto
Color

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
