#!/usr/bin/env bash
#
# System tune in chroot
set -e

name="${1}"
password="${2}"
zone="${3}"
sboot="${4}"
lang="${5}"

echo '- CHROOT'

# Tune the system
bsdtar --uid 0 --gid 0 -x -f /mnt/cfg.tar -C /

ln -sf /etc/pam.d/{su,su-l}
hwclock -w --utc
python3 /usr/local/bin/hostnamegen > /etc/hostname
chmod 444 /etc/hostname
chattr +i /etc/hostname

rm -rf /usr/share/applications/*

setcap 'CAP_SYS_NICE=eip' $(command -v gamescope)
echo '$layout = us,'"${lang}" > /etc/hypr/layout.conf

# Main
ln -sf "/usr/share/zoneinfo/${zone}" /etc/localtime
rm -f /etc/skel/.bash* /etc/skel/{atp,trash}/.gitkeep
useradd -m -G 'wheel,video' -s /usr/bin/zsh "${name}"
echo "${name}:${password}" | chpasswd
pacman -Scc --noconfirm

systemctl enable \
  systemd-networkd systemd-resolved systemd-networkd-persistent-storage \
  systemd-timesyncd fstrim.timer reflector.timer

systemctl mask sshd systemd-networkd-wait-online

# Secure Boot setup
if [[ "${sboot}" == 'y' ]]; then
  sbctl create-keys
  sbctl enroll-keys --microsoft
  sbctl sign -s /boot/vmlinuz-linux-zen
  sbctl sign -s -o /usr/lib/systemd/boot/efi/systemd-bootx64.efi{.signed,}
fi

# systemd-boot
bootctl install --esp-path=/boot

echo '- Exiting chroot'
