#!/usr/bin/sh
#
# Download and run the main script

set -e
readonly path='/tmp/njk'

# net tweaks
sysctl -w net.ipv4.tcp_timestamps=0
sysctl -w net.ipv4.tcp_fastopen=3
sysctl -w net.core.somaxconn=8192
sysctl -w net.ipv4.tcp_ecn=1
sysctl -w net.ipv4.tcp_congestion_control='bbr'

mkdir -p /etc/systemd/{resolved,timesyncd}.conf.d

cat << 'EOF' > /etc/systemd/resolved.conf.d/dns.conf
[Resolve]
DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
FallbackDNS=8.8.8.8#dns.google 8.8.4.4#dns.google 2001:4860:4860::8888#dns.google 2001:4860:4860::8844#dns.google
Domains=~.
Cache=yes
DNSOverTLS=yes
DNSSEC=true
EOF

cat << 'EOF' > /etc/systemd/timesyncd.conf.d/ntp.conf
[Time]
NTP=time.cloudflare.com
FallbackNTP=pool.ntp.org
EOF

systemctl daemon-reload
systemctl restart systemd-{timesyncd,resolved,networkd}

# main
curl -fLo "${path}i" \
  'https://github.com/nedorazrab0/arch-install/releases/download/rolling/njki'
echo
sha="$(openssl sha256 ${path}i | cut -d ' ' -f2)"
shapart="${sha:0:2}-${sha:2:3}-${sha:5:3}--${sha:8:2}-${sha:10:3}-${sha:13:3}"

echo '- SHA256 Part:'
echo "  ${shapart}"
sleep 2

[[ -d "${path}" ]] && rm -rf "${path}"
mkdir -p "${path}"
zstd -dc "${path}i" | bsdtar -x -C "${path}"
rm -f "${path}i"
exec sh "${path}/main"
