#!/usr/bin/env bash
set -e

# install configurating
kbl='#'
read -p '- Username: ' name
read -sp '- Password: ' password; echo
read -p '- Locale (en_US is preinstalled): ' kbl
read -p '- Timezone (e.g. Europe/Moscow): ' zone
read -p '- Target disk name: ' disk
read -p '- Do you want to destroy your own disk? (y/n): ' agreement

case "$agreement" in
    y) true;;
    n) exit 0;;
    *) exit 1;;
esac

# disk tuning
sysctl -w vm.vfs_cache_pressure=150
sysctl -w vm.dirty_bytes=268435456
sysctl -w vm.dirty_background_bytes=134217728
sysctl -w vm.dirty_writeback_centisecs=1500

sbd="/dev/$disk"
echo 'none' > $sbd/queue/scheduler
echo '128' > $sbd/queue/nr_requests
echo '2' > $sbd/queue/rq_affinity

# disk partition
echo '- You have 2 seconds to save your disk!'
sleep 2
cd /
blk="/dev/$disk"
umount -v $blk* || true
umount -vR /mnt || true
echo '- Disk partitioning...'
sgdisk -Zo -n1::+64M -t1:ef00 -c1:'EFI System Partition' \
           -n2::+ -t2:8304 -c2:'Arch Linux Root' -p $blk

mkfs.fat -vF32 -S512 -n 'ESP' --codepage=437 $blk*1
mkfs.btrfs -fKL 'archlinux' -n65536 -m single $blk*2

mount -t btrfs -o 'noatime,nodiscard,ssd,compress=zstd:3' $blk*2 /mnt
mount -t vfat -o 'noexec,nodev,nosuid,noatime,umask=0077,X-mount.mkdir' $blk*1 /mnt/boot

# installing
pacstrap -KP /mnt base linux-zen booster linux-firmware amd-ucode \
                  btrfs-progs f2fs-tools xfsprogs exfatprogs dosfstools gptfdisk \
                  android-tools opendoas git bash-completion {un,}zip gnome-boxes flatpak zram-generator nano reflector \
                  hyprland polkit xdg-desktop-portal-hyprland mako kitty noto-fonts waybar brightnessctl \
                  grim slurp vulkan-radeon libva-mesa-driver bluez{,-utils} pipewire{,-alsa,-pulse,-jack}
echo -e "en_US.UTF-8 UTF-8\n${kbl}.UTF-8 UTF-8" >> /mnt/etc/locale.gen

mount --bind /tmp/njk /mnt/mnt
arch-chroot /mnt bash /mnt/inchroot "$name" "$password" "$zone"

# post configuration
cfg='/tmp/njk/cfg'
cat $cfg/style.css > /mnt/etc/xdg/waybar/style.css
cat $cfg/config.jsonc > /mnt/etc/xdg/waybar/config.jsonc
cp $cfg/hyprland.conf /mnt/etc/hyprland.conf
rm -f /usr/share/applications/{qv4l2,qvidcap,bvnc,bssh,avahi-discover}.desktop

echo 'DefaultTimeoutStopSec=5s' >> /mnt/etc/systemd/system.conf
echo 'SleepOperation=suspend' >> /mnt/etc/systemd/logind.conf
cat /etc/systemd/timesyncd.conf > /mnt/etc/systemd/timesyncd.conf
cp $cfg/zram-generator.conf /mnt/etc/systemd
cat $cfg/loader.conf > /mnt/boot/loader/loader.conf
cp $cfg/arch-zen.conf /mnt/boot/loader/entries/arch-zen.conf
cp $cfg/{20-wired,25-wireless}.network /mnt/etc/systemd/network
mkdir -p /etc/systemd/system/systemd-networkd-wait-online.service.d
echo -e '[Service]\nExecStart=\nExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any' \
        > /etc/systemd/system/systemd-networkd-wait-online.service.d/wait-for-only-one-interface.conf

echo 'nedocomp' > /mnt/etc/hostname
echo 'permit persist :wheel' > /mnt/etc/doas.conf
chmod 400 /mnt/etc/doas.conf
cat $cfg/bash.bashrc > /etc/bash.basbrc
cp $cfg/60-ioschedulers.rules /mnt/etc/udev/rules.d
cp $cfg/99-sysctl.conf /mnt/etc/sysctl.d
cat /etc/xdg/reflector/reflector.conf > /mnt/etc/xdg/reflector/reflector.conf
cat $cfg/nanorc > /mnt/etc/nanorc

for scr in atp wlc wqc mnt scr fin h psg; do
    cp "/mnt/usr/bin/$scr"
    chmod 755 "/mnt/usr/bin/$scr"
done

echo '- Goodbye ;)'
sleep 2
fstrim -v /mnt
umount -vR /mnt
systemctl poweroff
