autoload -Uz compinit
compinit

setopt rm_star_silent

zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true

n=$'\n'
PROMPT="%B%F{#F2074D}%#%? %F{#48D8DB}%d%F{nocolor}${n}%b"
RPROMPT="%B%F{#33CCBB}%n@%M%F{nocolor}%b"

bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[l' clear-screen
