name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing `libarchive-tools`
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-tools

      - name: Archiving cfg/
        run: |
          chmod 755 ./cfg/usr/local/bin
          bsdtar -b1 -cv ./cfg/* > ./cfg.tar
          rm -rf ./cfg

      - name: Compressing
        run: |
          bsdtar \
            --exclude-vcs --exclude=./{.github/,README.md} -b1 -cv ./* \
            | zstd -T0 --ultra -20zvc > ./y2ai.tar.zst

      - name: Calculating hash
        run: |
          sha="$(openssl sha256 ./y2ai.tar.zst | cut -d ' ' -f2)"
          echo "shapart=${sha:0:2}-${sha:2:3}-${sha:5:3}-\
          -${sha:8:2}-${sha:10:3}-${sha:13:3}" | tee -a "${GITHUB_ENV}"

      - name: Releasing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release=test
          [[ "${release}" == 'test' ]] && flag='-p'
          gh release delete "${release}" --cleanup-tag -y || true
          printf "SHA256 Part:\n\`${shapart}\`" \
            | gh release create "${release}" ${flag} ./y2ai.tar.zst -F-
