name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete old release
        run: gh release delete rolling --cleanup-tag -y || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Install `libarchive-tools`
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-tools

      - name: Archive cfg/
        run: |
          chmod -R 755 ./cfg/usr/local/bin
          bsdtar -b1 -C ./cfg -cv . > ./cfg.tar
          rm -rf ./cfg

      - name: Compress
        run: |
          bsdtar \
            --exclude-vcs --exclude=./{.github/,README.md} -b1 -cv ./* \
            | lz4 -12zvc --favor-decSpeed > ./y2ai.tar.lz4

      - name: Calculate hash
        run: |
          xxh="$(xxhsum -H2 ./y2ai.tar.lz4 | cut -d ' ' -f1)"
          echo "xxhpart=${xxh:0:2}-${xxh:2:3}-${xxh:5:3}-\
          -${xxh:8:2}-${xxh:10:3}-${xxh:13:3}" | tee -a "${GITHUB_ENV}"

      - name: Release
        run: |
          gh release delete rolling --cleanup-tag -y || true
          printf "XXH128 Part:\n\`${shapart}\`" \
            | gh release create rolling ./y2ai.tar.lz4 -F-
        env:
          GH_TOKEN: ${{ github.token }}
